### ISSUE TITLE
NGinX example doesnt work

### ISSUE THREAD

**Issue by ihmc3jn09hk** [dambrogia/docker-testing#3]
Hi Dambrogia, thank you so much for your example. The idea behind decoupling ( in ur term "Containerization") is what I am looking for on a project gonna host on Cloud-based Host. The Apache example works like a charm but I cannot get the NginX example working with the example code given.
Did I missed something ??
"File Not Found" shown

**Comment by ihmc3jn09hk** [comment]
A careless point. I should have replaced the mounting for php to the one used by NginX.

**Comment by dambrogia** [comment]
Hi! @ihmc3jn09hk apologies for the late response. Glad you found this helpful and were able to get this all sorted out. Please let me know if you need help with anything else!
